//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhana4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Доставка.
    /// </summary>
    // *** Start programmer edit section *** (Доставка CustomAttributes)

    // *** End programmer edit section *** (Доставка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДоставкаE", new string[0])]
    [View("ДоставкаL", new string[0])]
    public class Доставка : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Snezhana4.ТипДоставки fТипДоставки;
        
        // *** Start programmer edit section *** (Доставка CustomMembers)

        // *** End programmer edit section *** (Доставка CustomMembers)

        
        /// <summary>
        /// ТипДоставки.
        /// </summary>
        // *** Start programmer edit section *** (Доставка.ТипДоставки CustomAttributes)

        // *** End programmer edit section *** (Доставка.ТипДоставки CustomAttributes)
        public virtual IIS.Snezhana4.ТипДоставки ТипДоставки
        {
            get
            {
                // *** Start programmer edit section *** (Доставка.ТипДоставки Get start)

                // *** End programmer edit section *** (Доставка.ТипДоставки Get start)
                IIS.Snezhana4.ТипДоставки result = this.fТипДоставки;
                // *** Start programmer edit section *** (Доставка.ТипДоставки Get end)

                // *** End programmer edit section *** (Доставка.ТипДоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доставка.ТипДоставки Set start)

                // *** End programmer edit section *** (Доставка.ТипДоставки Set start)
                this.fТипДоставки = value;
                // *** Start programmer edit section *** (Доставка.ТипДоставки Set end)

                // *** End programmer edit section *** (Доставка.ТипДоставки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДоставкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоставкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоставкаE", typeof(IIS.Snezhana4.Доставка));
                }
            }
            
            /// <summary>
            /// "ДоставкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоставкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоставкаL", typeof(IIS.Snezhana4.Доставка));
                }
            }
        }
    }
}
