//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhana4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Способ1.
    /// </summary>
    // *** Start programmer edit section *** (Способ1 CustomAttributes)

    // *** End programmer edit section *** (Способ1 CustomAttributes)
    public enum Способ1
    {
        
        // *** Start programmer edit section *** (Способ1.4 CustomAttributes)

        // *** End programmer edit section *** (Способ1.4 CustomAttributes)
        [Caption("Банковской картой")]
        4,
        
        // *** Start programmer edit section *** (Способ1.2 CustomAttributes)

        // *** End programmer edit section *** (Способ1.2 CustomAttributes)
        [Caption("Электронные деньги")]
        2,
        
        // *** Start programmer edit section *** (Способ1.1 CustomAttributes)

        // *** End programmer edit section *** (Способ1.1 CustomAttributes)
        [Caption("Спб")]
        1,
        
        // *** Start programmer edit section *** (Способ1.3 CustomAttributes)

        // *** End programmer edit section *** (Способ1.3 CustomAttributes)
        [Caption("При получении")]
        3,
    }
}
